ALTER TABLE quotes ADD COLUMN id_uuid CHAR(36) NULL;
UPDATE quotes SET id_uuid = UUID() WHERE id_uuid IS NULL;
ALTER TABLE quotes DROP PRIMARY KEY;
ALTER TABLE quotes DROP COLUMN id;
ALTER TABLE quotes CHANGE COLUMN id_uuid id CHAR(36) NOT NULL;
ALTER TABLE quotes ADD PRIMARY KEY (id);
