openapi: 3.0.3
info:
  title: Song Quotes Service API
  version: 1.0.0
  description: Aggregated OpenAPI definition for the Song Quotes Service endpoints.
servers:
  - url: /api
  - url: /
paths:
  /artist/{id}:
    $ref: './artist-api.yaml#/paths/~1artist~1{id}'
  /artists:
    $ref: './artist-api.yaml#/paths/~1artists'
  /admin/quote:
    $ref: './admin-api.yaml#/paths/~1admin~1quote'
  /admin/quotes:
    $ref: './admin-api.yaml#/paths/~1admin~1quotes'
  /admin/quotes/reset-hits:
    $ref: './admin-api.yaml#/paths/~1admin~1quotes~1reset-hits'
  /admin/quote/{id}:
    $ref: './admin-api.yaml#/paths/~1admin~1quote~1{id}'
  /admin/export:
    $ref: './admin-api.yaml#/paths/~1admin~1export'
  /quotes:
    $ref: './quote-api.yaml#/paths/~1quotes'
  /quotes/count:
    $ref: './quote-api.yaml#/paths/~1quotes~1count'
  /quote/random:
    $ref: './quote-api.yaml#/paths/~1quote~1random'
  /quote/{id}:
    $ref: './quote-api.yaml#/paths/~1quote~1{id}'
  /quotes/top10:
    $ref: './quote-api.yaml#/paths/~1quotes~1top10'
  /ping:
    $ref: './ping-api.yaml#/paths/~1ping'
  /secure/ping:
    $ref: './ping-api.yaml#/paths/~1secure~1ping'
components:
  schemas:
    Quote:
      $ref: './components/schemas.yaml#/components/schemas/Quote'
    Artist:
      $ref: './components/schemas.yaml#/components/schemas/Artist'
    ArtistTrack:
      $ref: './components/schemas.yaml#/components/schemas/ArtistTrack'
    ArtistQuoteCount:
      $ref: './components/schemas.yaml#/components/schemas/ArtistQuoteCount'
