debug: false

spring:
  application:
    name: song-quotes-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://http://192.168.1.139:32080/realms/xavelo
          jwk-set-uri: https://http://192.168.1.139:32080/realms/xavelo/protocol/openid-connect/certs
  datasource:
    url: jdbc:mysql://sqs-mysql.mysql.svc.cluster.local:3306/song-quotes
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  kafka:
    bootstrap-servers: my-kafka-kafka-bootstrap.kafka.svc.cluster.local:9092
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQLDialect
  flyway:
    baseline-on-migrate: true
    mysql:
      enabled: true

spotify:
  api:
    url: https://api.spotify.com/v1
    clientId: ${SPOTIFY_CLIENT_ID}
    clientSecret: ${SPOTIFY_CLIENT_SECRET}

quote-events:
  outbox:
    worker:
      batch-size: 50

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"
  endpoint:
    prometheus:
      enabled: true
