debug: false

spring:
  application:
    name: song-quotes-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://http://192.168.1.139:32080/realms/xavelo
          jwk-set-uri: https://http://192.168.1.139:32080/realms/xavelo/protocol/openid-connect/certs
  datasource:
    url: jdbc:mysql://sqs-mysql.mysql.svc.cluster.local:3306/song-quotes
    driverClassName: com.mysql.cj.jdbc.Driver
    username: xavelo
    password: sqs
  kafka:
    bootstrap-servers: my-kafka-kafka-bootstrap.kafka.svc.cluster.local:9092
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQLDialect
  flyway:
    mysql:
      enabled: true
spotify:
  api:
    url: https://api.spotify.com/v1
    clientId: ${SPOTIFY_CLIENT_ID}
    clientSecret: ${SPOTIFY_CLIENT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"
  endpoint:
    prometheus:
      enabled: true
logging:
  level:
    org.springframework.security: INFO
    org.flyway: INFO
    com.xavelo.sqs.application.service: DEBUG
