ALTER TABLE quotes ADD COLUMN id_uuid CHAR(36);
UPDATE quotes SET id_uuid = CAST(RANDOM_UUID() AS VARCHAR(36)) WHERE id_uuid IS NULL;
ALTER TABLE quotes DROP PRIMARY KEY;
ALTER TABLE quotes DROP COLUMN id;
ALTER TABLE quotes ALTER COLUMN id_uuid RENAME TO id;
ALTER TABLE quotes ALTER COLUMN id SET DATA TYPE CHAR(36);
ALTER TABLE quotes ALTER COLUMN id SET NOT NULL;
ALTER TABLE quotes ADD PRIMARY KEY (id);
