apiVersion: apps/v1
kind: Deployment
metadata:
  name: song-quotes-service-deployment
  annotations:
    commitID: "ad12cab60731401856102dee89ec4f97b4e36f70"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: song-quotes-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: song-quotes-service
    spec:
      containers:
        - name: song-quotes-service
          image: 'xavelo/song-quotes-service:ad12cab60731401856102dee89ec4f97b4e36f70'
          ports:
            - containerPort: 80
