apiVersion: apps/v1
kind: Deployment
metadata:
  name: song-quotes-deployment
  annotations:
    commitID: "39e7ca5480d1ea5b7a3280672ae6de2d60769116"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: song-quotes
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: song-quotes
    spec:
      containers:
        - name: song-quotes-service
          image: 'xavelo/song-quotes-service:39e7ca5480d1ea5b7a3280672ae6de2d60769116'
          ports:
            - containerPort: 80
