apiVersion: apps/v1
kind: Deployment
metadata:
  name: song-quotes-deployment
  annotations:
    commitID: "f335dff95a98111c876c4115f67640fb29ff26b2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: song-quotes
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: song-quotes
    spec:
      containers:
        - name: song-quotes-service
          image: 'xavelo/song-quotes-service:f335dff95a98111c876c4115f67640fb29ff26b2'
          ports:
            - containerPort: 80
